project:
  type: website
  output-dir: docs

website:
  title: "Enseñando Tecnología en Comunidad"
  sidebar:
    background: primary
    # logo: "images/logo.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/yabellini/t3es
        text: GitHub
    style: docked
    contents:
      - href: index.qmd
        text: Inicio
      - href: intro-personas.qmd
        text: Lección 1 - Introducción y personas
      - href: intro-personas.qmd
        text: Lección 2 - Modelos mentales
      - href: carga-cognitiva.qmd
        text: Lección 3 - Carga cognitiva
      - href: capacidad-cognitiva.qmd
        text: Lección 4 - Capacidad cognitiva
      - href: feedback.qmd
        text: Lección 5 - Crítica - Devolución - Feedback
      - href: evaluacion.qmd
        text: Lección 6 - Evaluación
      - href: schedule.qmd
        text: Agenda
      - href: materials.qmd
        text: Materialess


format:
  html:
    theme: cosmo
    # css: styles.css
    toc: true

execute:
  freeze: auto

