---
title: "Enseñando Tecnología en Comunidad"
---

Este curso es una Una introducción a la enseñanza basada en evidencia científica para personas con formación técnica.

Está basado en los materiales del libro [Enseñar Tecnología en Comunidad](https://educarencomunidad.tech/) ([Teaching Tech Together](https://teachtogether.tech/)) de [Greg Wilson](https://third-bit.com/) (2019).

## ¿Para quién es este curso?

El curso está pensado para cualquier persona que esté interesada en mejorar sus habilidades
como docente.

Los cuatro tipos de personas a las que está destinado este curso son _enseñantes finales_, lo que significa que la enseñanza no es su ocupación primaria, tienen poco o ningún conocimiento sobre pedagogía y posiblemente no enseñan en clases de instituciones educativas formales.

* **Emilia**: está entrenada como bibliotecaria y actualmente trabaja como diseñadora web y gestora de proyectos en una pequeña empresa consultora. En su tiempo libre, ayuda a impartir clases de diseño para mujeres que ingresan a la tecnología como una segunda carrera. Se encuentra reclutando colegas para dar más clases en su área y quiere saber cómo preparar lecciones que otras personas puedan usar, a la par de hacer crecer una organización de enseñanza voluntaria.

* **David**: es un programador profesional, cuyos dos hijos adolescentes asisten a una escuela que no ofrece clases de programación. Se ha ofrecido como voluntario para dirigir un club de programación mensual después del horario de clases. A pesar de que expone presentaciones frecuentemente a sus colegas, no tiene experiencia enseñando en el aula. Quiere aprender a construir lecciones efectivas en un tiempo razonable, y le gustaría aprender más acerca de los pros y contras de las clases en línea en las que cada asistente cursa a su propio ritmo.

* **Samira**: es una estudiante de robótica, que está considerando ser docente luego de graduarse. Quiere ayudar en unos talleres de robótica que se dictan los fines de semana, pero nunca ha enseñado antes, por lo que siente síndrome de la impostora{síndrome del impostor/a}. Quiere aprender más acerca de educación en general para decidir si la docencia es para ella y también está buscando sugerencias específicas que la ayuden a dar clase de forma más efectiva.

* **René**: es docente de ciencias de la computación en una universidad. Ha estado enseñando cursos de grado sobre sistemas operativos por seis años y cada vez se convence más de que tiene que haber una mejor manera de enseñar. El único entrenamiento disponible a través de su universidad está relacionado con la herramienta del sistema de gestión del aprendizaje en línea, por lo que quiere descubrir qué otro tipo de entrenamiento podría pedir.

Este taller práctico cubre las bases de la psicología de educación, la ciencia del aprendizaje y la enseñanza, el diseño instruccional y muestra como utilizar estas ideas en talleres intensivos y clases regulares.

El curso es un conjunto de clases y ejercicios prácticos donde ensayarás dar una lección corta utilizando las herramientas aprendidas e implementando algunas de las técnicas de enseñanza que discutiremos. 

Este es un curso para aprender a enseñar tecnología, no necesitas tener experiencia sobre un lenguaje de programación o una herramienta técnica, ya que no lo cubriremos en este curso.

## ¿Cómo usar este material?

Si quieres usar este material para enseñar, en cada lección vas a encontrar los objetivos de aprendizaje, las diapositivas y ejemplos de los documentos compartidos utilizados.  

En la sección [agenda](schedule.html) vas a encontrar un ejemplo de organización de las lecciones y en la sección [material](/materials.html) vas a encontrar un listado de los recursos que utilizamos para armar este taller. 

Podes copiar, re usar y adaptar este material para tus propios talleres.  Lo que te pedimos es que nos des crédito por el material y cumplas con la licencia que detallamos a continuación.

## Lecciones

* [Lección 1 - Introducción y personas](/intro-personas.html)
* [Lección 2 - Modelos mentales](/modelos-mentales.html)
* [Lección 3 - Carga cognitiva](/carga-cognitiva.html)
* [Lección 4 - Capacidad cognitiva](/capacidad-cognitiva.html)
* [Lección 5 - Crítica - Devolución - Feedback](/feedback.html)
* [Lección 6 - Evaluación](/evaluacion.html)
* [Lección 7 - Motivación](/motivacion.html)
* [Lección 8 - Aprendizaje](/aprendizaje.html)
* [Lección 9 - Preparándote para Enseñar](/preparacion.html)
* [Lección 10 - Mitos educativos y reglas para enseñar](/mitos-reglas.html)

## Licencia

Esta obra está bajo licencia [Atribución-CompartirIgual 4.0 Internacional ](https://creativecommons.org/licenses/by-sa/4.0/deed.es) (CC BY-SA 4.0).


## ¿Cómo citar este trabajo?

Bellini Saibene, Yanina; Corrales, Paola. 

## Fuentes

Como mencionamos la mayor parte de este material se derivó del Libro Enseñar Tecnología en Comunidad (Teaching Tech Together) que se está actualizando en la [segunda edición de Enseñar Tecnología en Comunidad](https://teachingtechtogether.netlify.app/).  

También utilizamos material del [entrenamiento para instructores de Posit (ex RStudio) Education](https://education.rstudio.com/trainers/#info) creado por [Greg Wilson](https://third-bit.com/) y el [entrenamiento para instructores de The Carpentries](https://carpentries.github.io/instructor-training).   
