---
title: "Motivación"
---

## Objetivos de aprendizaje

1. Describir la diferencia entre motivación intrínseca y extrínseca.
2. Resumir tres factores principales de motivación y desmotivación de estudiantes adultos neurotípicos.
3. Definir el término "falso principiante", explicarlo en términos de modelos mentales y explicar los desafíos especiales que los falsos principiantes presentan en la enseñanza.
4. Explicar los peligros de la pre-evaluación y como se relaciona con la motivación.
5. Describir que acciones se pueden tomar como docente para contribuir a la inclusión en clase.
6. Explicar el papel de los escenarios y los juegos de rol en la adquisición de habilidades de persona aliada.
7. Describir y justificar los pasos que debe dar un/a docente si tiene que expulsar a un/a estudiante de su clase.


## Slides

<iframe src="https://docs.google.com/presentation/d/198w0fFnYWD-8x5N61cnXCjQd5GLJNA7G0fAgiyMyFD4/embed?start=false&loop=false&delayms=3000" frameborder="0" width="760" height="569" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true"></iframe>

